services:
  - title: "21st EAI International Conference on Mobile and Ubiquitous Systems: Computing, Networking and Services (MobiQuitous 2024)"
    role: Workshop Co-chair
    conference: y

  - title: "2024 IEEE International Conference on Communications, Control, and Computing Technologies for Smart Grids (SmartGridComm),  Workshop on Optimal and Green Operation of Multi-energy Smart Grids"
    role: PC Co-chair
    conference: y
    
  - title: "ICDE 2025, AAAI 2024-2025, IJCAI 2024, KDD 2023-2025, CIKM 2022-2024, SDM 2024, IEEE BigData 2024"
    role: PC Member
    conference: y
    
 <!-- - title: "Mathematics, Special Issue \"Mathematical Modeling for Parallel and Distributed Processing\""-->
 <!--  role: Leading Guest Editor-->
 <!--  journal: y-->

 <!--- title: "The institution of Engineering and Technology (IET), Special Issue \"Distributed Optimization and Machine Learning for Resilient Energy Systems\""-->
 <!--   role: Guest Editor-->
 <!--  journal: y-->


 
  
